import { NextPage } from "next";
import type { Metadata } from "next";

type Props = {
  params: {
    slug: string;
  };
};

export const metadata: Metadata = {
  title: "Post Nathan",
  description: "Generated by create next app",
};

const BlogPost: NextPage<Props> = ({ params }) => {
  console.log(params);
  return <div className="About">Sobre mi</div>;
};

export default BlogPost;
